apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: imdb-sentiment-client
      labels:
        app.kubernetes.io/name: imdb-client
    spec:
      type: LoadBalancer
      ports:
          - name: http
            port: 5000
            targetPort: 5000
      selector:
        app.kubernetes.io/name: imdb-client

# APP Environment
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: imdb-client
      labels:
        app.kubernetes.io/name: imdb-client
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app.kubernetes.io/name: imdb-client
        spec:
          containers:
            - image: docker.io/lapolonio/imdb_client:v3
              name: imdb-client
              env:
                  - name: APP_CONFIG_FILE
                    value: "config/production.py"
              command: ["pipenv", "run", "python", "run_app.py"]
              ports:
                - name: http
                  containerPort: 5000
              resources:
                requests:
                  cpu: 200m
                  memory: 256Mi
                limits:
                  cpu: 2
                  memory: 2Gi
kind: List
metadata: {}
