apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: imdb-sentiment-service
      labels:
        app.kubernetes.io/name: imdb-server
    spec:
      type: LoadBalancer
      ports:
        # EXPOSE BERT SERVER
        - name: "grpc"
          port: 8500
          targetPort: 8500
        - name: "rest"
          port: 8501
          targetPort: 8501
      selector:
        app.kubernetes.io/name: imdb-server

# APP Environment
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: imdb-server
      labels:
        app.kubernetes.io/name: imdb-server
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app.kubernetes.io/name: imdb-server
        spec:
          containers:
            - image: tensorflow/serving:latest-gpu
              name: imdb-model
              env:
                - name: MODEL_NAME
                  value: "bert"
              ports:
                - name: grpc
                  containerPort: 8500
                - name: rest
                  containerPort: 8501
              resources:
                requests:
                  cpu: 200m
                  memory: 256Mi
                limits:
                  cpu: 2
                  memory: 2Gi
              volumeMounts:
                - name: model-repo
                  mountPath: /models
          volumes:
            - name: model-repo
              persistentVolumeClaim:
                claimName: model-repo-storage
kind: List
metadata: {}
