apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: agnews-client-service
      labels:
        app.kubernetes.io/name: agnews-client
    spec:
      type: LoadBalancer
      ports:
        # EXPOSE BERT CLIENT
        - name: "http"
          port: 5000
          targetPort: 5000
      selector:
        app.kubernetes.io/name: agnews-client

    - apiVersion: v1
      kind: Service
      metadata:
        name: agnews-server-service
        labels:
          app.kubernetes.io/name: agnews-server
      spec:
        type: LoadBalancer
        ports:
          # EXPOSE BERT SERVER
          - name: "grpc"
            port: 8500
            targetPort: 8500
          - name: "rest"
            port: 8501
            targetPort: 8501
        selector:
          app.kubernetes.io/name: agnews-server

# APP Environment
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: agnews-app
      labels:
        app.kubernetes.io/name: agnews-app
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app.kubernetes.io/name: agnews-app
        spec:
          containers:
            - image: lapolonio/bert_agnews_client:v3
              name: agnews-client
              ports:
                - name: http
                  containerPort: 5000
              resources:
                requests:
                  nvidia.com/gpu: 1
                  cpu: 1
                  memory: 1Gi
                limits:
                  nvidia.com/gpu: 1
                  cpu: 8
                  memory: 8Gi
            - image: tensorflow/serving:latest-gpu
              name: agnews-model
              env:
                - name: MODEL_NAME
                  value: "bert"
              ports:
                - name: grpc
                  containerPort: 8500
                - name: rest
                  containerPort: 8501
              resources:
                requests:
                  cpu: 200m
                  memory: 256Mi
                limits:
                  cpu: 2
                  memory: 2Gi
              volumeMounts:
                # - name: init-script-configmap
                #   mountPath: /scripts
                - name: model-repo
                  mountPath: /models
          volumes:
            - name: model-repo
              persistentVolumeClaim:
                claimName: model-repo-storage
kind: List
metadata: {}
